require: rubocop-rspec

Rails:
  Enabled: true

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'app/assets/**/*'
    - 'config/**/*'
    - 'doc/**/*'
    - 'spec/**/*'
    - 'test/**/*'

Style/Encoding:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/Documentation:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 106
  Exclude:
    - 'app/controllers/users/sessions_controller.rb'  

Metrics/AbcSize:
  Max: 23

Metrics/PerceivedComplexity:
  Max: 9

Metrics/CyclomaticComplexity:
  Max: 9

Style/NumericPredicate:
  Exclude:
    - 'app/models/user.rb'

Style/AndOr:
  Exclude:
    - 'app/controllers/application_controller.rb'

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/users/sessions_controller.rb'

Style/MutableConstant:
  Exclude:
    - 'lib/dmr/splunk_api_helper.rb'

Style/ConditionalAssignment:
  Exclude:
    - 'lib/dmr/splunk_api_helper.rb'

Style/AlignHash:
  Enabled: false

Style/SignalException:
  Exclude:
    - 'app/models/user.rb'

Style/NegatedIf:
  Exclude:
    - 'lib/dmr/splunk_api_helper.rb'
    - 'lib/dmr/course_controller_helper.rb'

Metrics/ModuleLength:
  Exclude:
    - 'lib/dmr/controller_helper.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/courses_controller.rb'

Metrics/MethodLength:
  Max: 17
  Exclude:
    - 'lib/dmr/course_controller_helper.rb'

Style/BlockDelimiters:
  Exclude:
    - 'lib/dmr/splunk_api_helper.rb'

