version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.7-jessie-node
    environment:
      RAILS_ENV: test
    steps:
      - checkout
      - restore_cache:
          keys:
          - bundle-v1-{{ checksum "Gemfile.lock" }}
      - run:
          name: Update Bundler
          command: gem update bundler
      - run:
          name: Run Bundle Install
          command: bundle check || bundle install --path vendor/bundle --jobs 4 --retry 3
      - save_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - "vendor/bundle"
      - run:
          name: Rubocop
          command: bundle exec rubocop
      - run:
          name: Setup Database
          command: bundle exec rake db:migrate RAILS_ENV=test
      - run:
          name: Run Test Suite
          command: bundle exec rspec spec
