# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

defaults: &defaults
  ldap_host: <%= ENV['APPS_DMR_LDAP_HOST'] %>
  ldap_port: <%= ENV['APPS_DMR_LDAP_PORT'] %>
  ldap_base: <%= ENV['APPS_DMR_LDAP_BASE'] %>
  ldap_username: <%= ENV['APPS_DMR_LDAP_USER'] %>
  ldap_password: <%= ENV['APPS_DMR_LDAP_PASS'] %>
  ldap_group: <%= ENV['APPS_DMR_LDAP_GROUP'] %>
  splunk_uri: <%= ENV['APPS_DMR_SPLUNK_URI'] %>
  splunk_username: <%= ENV['APPS_DMR_SPLUNK_USER'] %>
  splunk_password: <%= ENV['APPS_DMR_SPLUNK_PASS'] %>

development:
  secret_key_base: <%= ENV['APPS_DMR_DEV_SECRET_KEYBASE'] %>

test:
  secret_key_base: <%= ENV['APPS_DMR_TEST_SECRET_KEYBASE'] %>

production:
  <<: *defaults
  secret_token:: <%= ENV['APPS_DMR_PROD_SECRET_TOKEN'] %>
  secret_key_base: <%= ENV['APPS_DMR_PROD_SECRET_KEYBASE'] %>

staging:
  <<: *defaults
  secret_token:: <%= ENV['APPS_DMR_STAGING_SECRET_TOKEN'] %>
  secret_key_base: <%= ENV['APPS_DMR_STAGING_SECRET_KEYBASE'] %>

pontos:
  <<: *defaults
  secret_token:: <%= ENV['APPS_DMR_PONTOS_SECRET_TOKEN'] %>
  secret_key_base: <%= ENV['APPS_DMR_PONTOS_SECRET_KEYBASE'] %>
